services:
  - type: web
    name: sistema-gestion-reservas
    runtime: python
    plan: free
    region: virginia
    buildCommand: bash build.sh
    startCommand: python -m gunicorn gestion_reservas_admin.gestion_reservas_admin.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
